// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNm9bInJPhx4C-QMFDvGUPmGBcTZiqWQ4',
    appId: '1:788358758157:web:52a33c61c5f95b56f8ba44',
    messagingSenderId: '788358758157',
    projectId: 'bsocial-9e6c3',
    authDomain: 'bsocial-9e6c3.firebaseapp.com',
    storageBucket: 'bsocial-9e6c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpK7HrlUzOLY62g49y68_pstz9YOPIMN0',
    appId: '1:788358758157:android:6f86989bf518ac14f8ba44',
    messagingSenderId: '788358758157',
    projectId: 'bsocial-9e6c3',
    storageBucket: 'bsocial-9e6c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLUk9FZTGu_T4CQv_Tm9xQmUBDxZeKSQs',
    appId: '1:788358758157:ios:1234567890abcdef',
    messagingSenderId: '788358758157',
    projectId: 'bsocial-9e6c3',
    storageBucket: 'bsocial-9e6c3.appspot.com',
    iosBundleId: 'com.example.bsocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLUk9FZTGu_T4CQv_Tm9xQmUBDxZeKSQs',
    appId: '1:788358758157:ios:1234567890abcdef',
    messagingSenderId: '788358758157',
    projectId: 'bsocial-9e6c3',
    storageBucket: 'bsocial-9e6c3.appspot.com',
    iosBundleId: 'com.example.bsocial.RunnerTests',
  );
}
